(#38) First update to latest 0.12 versions
Apply these versions with TF 0.12 and then TF 0.13 to avoid the
following error.

```
Error: Provider configuration not present

To work with
module.host.module.project.module.project-factory.null_resource.preconditions
its original provider configuration at
provider["registry.terraform.io/-/null"] is required, but it has been removed.
This occurs when a provider configuration is removed while objects created by
that provider still exist in the state. Re-add the provider configuration to
destroy
module.host.module.project.module.project-factory.null_resource.preconditions,
after which you can remove the provider configuration again.
```

Changes are expected:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.host.module.project.module.project-factory.null_resource.preconditions will be destroyed
  - resource "null_resource" "preconditions" {
      - id       = "8839499245402532934" -> null
      - triggers = {
          - "billing_account"  = "XXXXXXXXXXXXXXXXXXXX"
          - "credentials_path" = ""
          - "folder_id"        = "folders/XXXXXXXXXXXX"
          - "org_id"           = "XXXXXXXXXXXX"
          - "shared_vpc"       = ""
        } -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions in workspace "dev"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.host.module.project.module.project-factory.null_resource.preconditions: Destroying... [id=8839499245402532934]
module.host.module.project.module.project-factory.null_resource.preconditions: Destruction complete after 0s
```